-- 网站收藏表
CREATE TABLE IF NOT EXISTS website_bookmark (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL COMMENT '网站名称',
    url VARCHAR(1024) NOT NULL COMMENT '网站地址',
    account VARCHAR(255) DEFAULT NULL COMMENT '账号',
    password VARCHAR(255) DEFAULT NULL COMMENT '密码',
    description VARCHAR(512) DEFAULT NULL COMMENT '网站描述',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网站收藏表';
