server:
  port: 8080

spring:
  application:
    name: my-website
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:my_website;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# Python 服务配置
python:
  xmind:
    url: http://localhost:8001/parse-xmind
